import type { Metadata } from "next";
import { Monoton, Lato, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { PageWrapper } from "@/components/page-wrapper";

const titleFont = Monoton({
  weight: "400",
  subsets: ["latin"],
  variable: "--title-font",
});

const sansFont = Lato({
  weight: ["300", "400", "700", "900"],
  subsets: ["latin"],
  variable: "--sans-font",
});

const monoFont = IBM_Plex_Mono({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--mono-font",
});

export const metadata: Metadata = {
  title: "Artcade",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${titleFont.variable} ${sansFont.variable} ${monoFont} font-sans antialiased`}
      >
        <ThemeProvider
          attribute="class"
          themes={["dark"]}
          defaultTheme="dark"
          enableSystem={false}
        >
          <PageWrapper>{children}</PageWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
